added modules for getting a members repos and their links
kossiitkgp/profile-generator pull request #2
Opened 2017-05-03 21:35 UTC by aribis369

2017-05-04 06:46 UTC, dibyadas requested changes
This looks good overall. Just remove those debug comments and add some informative comments for other to follow up.

2017-05-04 06:46 UTC, dibyadas commented on app.py
> +            #print("https://www.github.com/"+j["full_name"])
@aribis369 Can you remove these comments?

2017-05-04 07:02 UTC, aribis369 commented
added comments will you try to render the html file by passing the repo and repolink list to it

2017-05-04 07:19 UTC, dibyadas commented on app.py
> +    # covrting to json
typo here

2017-05-08 06:32 UTC, dibyadas approved these changes

2017-05-08 06:32 UTC, merged